
export default [
    {
        'id': 1,
        'img': './assets/plant-images/monstera-deliciosa.jpg',
        'common-name': 'Swiss Cheese plant',
        'genus': 'Monstera  Deliciosa',
        'care-level': 3,
        'family': 'Aracea',
        'plant-type': 'Tropical, climbing evergreen',
        'mature-size': '3 ft. tall',
        'water': '',
        'sun-exposure': 'Bright indirect sunlight, partial shade',
        'soil-type': 'Peat based potting soil, well-drained',
        'soil-pH': 'Acidic or neutral',
        'growing-season': 'Mid-summer',
        'native-area': 'Central America',
        'propagation': 'Yes',
        'toxicity': 'Toxic to cats and dogs.',
    },
    {
        'id': 2,
        'common-name': 'Baby Rubber Plant/Radiator Plant',
        'genus': 'Peperomia',
        'care-level': 2,
        'family': 'Piperacea',
        'plant-type': 'Tropical Perennial',
        'mature-size': '6-12 in. tall',
        'water': '',
        'sun-exposure': 'Full or partial sunlight',
        'soil-type': 'Moist, well-drained soil',
        'soil-pH': 'Neutral to acidic.',
        'growing-season': 'Summer.',
        'native-area': 'Central America, South America, and the Caribbean',
        'propagation': 'Yes',
        'toxicity': 'Considered non-toxic and pet-friendly.',
    },
    {
        'id': 3,
        'common-name': 'Philodendron',
        'genus': 'Philodendron',
        'care-level': 1,
        'family': 'Araceae',
        'plant-type': 'Perennial',
        'mature-size': '1-20 ft. long',
        'water': '',
        'sun-exposure': 'Partial sunlight',
        'soil-type': 'Well-drained loam soil',
        'soil-pH': 'Acidic',
        'growing-season': 'Spring and Winter',
        'native-area': 'Central America and South America',
        'propagation': 'Yes',
        'toxicity': 'Toxic to pets and humans if ingested.',
    },
    {
        'id': 4,
        'common-name': 'Chinese Evergreen',
        'genus': 'Aglanoema Commutatum',
        'care-level': 1,
        'family': 'Araceae',
        'plant-type': 'Tropical Herbaceous Perennial',
        'mature-size': '1-2 ft. tall',
        'water': '',
        'sun-exposure': 'Full or partial sunlight',
        'soil-type': 'Well-drained peaty soil',
        'soil-pH': 'Acidic',
        'growing-season': 'Spring and Summer',
        'native-area': 'Asia',
        'propagation': 'Yes',
        'toxicity': 'Toxic to cats and dogs.',
    },
    {
        'id': 5,
        'common-name': 'ZZ Plant',
        'genus': 'Zamioculcas zamiifolia',
        'care-level': 1,
        'family': 'Araceae',
        'plant-type': 'Tropical Perennial',
        'mature-size': '3-4 ft. tall',
        'water': '',
        'sun-exposure': 'Bright to low indirect light',
        'soil-type': 'Well-drained',
        'soil-pH': 'Neutral to acidic',
        'growing-season': 'Spring',
        'native-area': 'Eastern Africa',
        'propagation': 'Yes',
        'toxicity': 'Midly toxic to humans and animals.',
    },
    {
        'id': 6,
        'common-name': 'Aloe Vera',
        'genus': 'Aloe Barbadensis Miller',
        'care-level': 1,
        'family': 'Asphodelaceae',
        'plant-type': 'Succulent',
        'mature-size': '1-2 ft. tall',
        'water': '',
        'sun-exposure': 'Direct sunlight',
        'soil-type': 'Well-drained and sandy',
        'soil-pH': 'Slightly acidic',
        'growing-season': ' Summer',
        'native-area': 'Africa, Arabian Peninsula, and Madagascar',
        'propagation': 'Yes',
        'toxicity': 'Midly toxic to humans and pets.',
    },
    {
        'id': 7,
        'common-name': 'Money Tree',
        'genus': 'Pachira Aquatica',
        'care-level': 1,
        'family': 'Malvaceae',
        'plant-type': 'Tree',
        'mature-size': '20-30 ft. tall (smaller indoors)',
        'water': '',
        'sun-exposure': 'Full sun or partial shade',
        'soil-type': 'Moist but well-drained',
        'soil-pH': 'Neutral to acidic',
        'growing-season': 'Summer',
        'native-area': 'South America',
        'propagation': 'Yes',
        'toxicity': 'Considered non-toxic and pet-friendly.',
    },
    {
        'id': 8,
        'common-name': 'Peace Lily',
        'genus': 'Spathiphyllum',
        'care-level': 2,
        'family': 'Araceae',
        'plant-type': 'Flowering Tropical Plant',
        'mature-size': '1-3 ft. tall',
        'water': '',
        'sun-exposure': 'Partial shade',
        'soil-type': 'Moist but well-drained',
        'soil-pH': 'Acidic',
        'growing-season': 'Spring',
        'native-area': 'Central America and Asia',
        'propagation': 'Yes',
        'toxicity': 'Toxic to humans and pets.',
    },
    {
        'id': 9,
        'common-name': 'Pothos',
        'genus': 'Epipremnum Aureum',
        'care-level': 1,
        'family': 'Araceae',
        'plant-type': 'Tropical vine',
        'mature-size': '20-40 ft. long',
        'water': '',
        'sun-exposure': 'Full sun or partial shade',
        'soil-type': 'Moist but well-drained',
        'soil-pH': 'Neutral to acidic',
        'growing-season': 'Spring and Winter',
        'native-area': 'South Pacific',
        'propagation': 'Yes',
        'toxicity': 'Toxic to pets.',
    },
    {
        'id': 10,
        'common-name': 'Rubber Plant',
        'genus': 'Ficus Elastica',
        'care-level': 2,
        'family': 'Euphorbiaceae',
        'plant-type': 'Evergreen Tree',
        'mature-size': '50-100 ft. tall (smaller indoors)',
        'water': '',
        'sun-exposure': 'Partial shade',
        'soil-type': 'Moist but well-drained',
        'soil-pH': 'Acidic',
        'growing-season': 'Summer',
        'native-area': 'Asia',
        'propagation': 'Yes',
        'toxicity': 'Toxic to pets.',
    },
    {
        'id': 11,
        'common-name': 'String of Hearts',
        'genus': 'Ceropegia Woodii',
        'care-level': 2,
        'family': 'Apocynaceae',
        'plant-type': 'Succulent, Vine',
        'mature-size': '1-2 ft. long',
        'water': '',
        'sun-exposure': 'Partial sun',
        'soil-type': 'Well-drained',
        'soil-pH': 'Neutral to acidic',
        'growing-season': 'Summer and Fall',
        'native-area': 'South Africa',
        'propagation': 'Yes',
        'toxicity': 'Considered non-toxic and pet-friendly.',
    },
    {
        'id': 12,
        'common-name': 'Snake Plant',
        'genus': 'Dracaena Trifasciata',
        'care-level': 1,
        'family': 'Asparagaceae',
        'plant-type': 'Evergreen Perennial',
        'mature-size': '6 in. to 2 ft. tall',
        'water': '',
        'sun-exposure': 'Shade to partial sun',
        'soil-type': 'Well-drained, sandy',
        'soil-pH': 'Slightly acidic to slightly alkaline',
        'growing-season': 'Spring',
        'native-area': 'West Africa',
        'propagation': 'Yes',
        'toxicity': 'Toxic to pets',
    },
    {
        'id': 13,
        'common-name': 'Aloe Tiki Zilla',
        'genus': 'Aloe',
        'care-level': 1,
        'family': 'Asphodelaceae',
        'plant-type': 'Succulent',
        'mature-size': '1-2 ft. tall',
        'water': '',
        'sun-exposure': 'Direct sunlight',
        'soil-type': 'Well-drained and sandy',
        'soil-pH': 'Slightly acidic',
        'growing-season': 'Summer',
        'native-area': 'Africa, Arabian Peninsula, and Madagascar',
        'propagation': 'Yes',
        'toxicity': 'Midly toxic to humans and pets.',
    },
    {
        'id': 14,
        'common-name': 'Jade Plant',
        'genus': 'Crassula',
        'care-level': 1,
        'family': 'Crassulaceae',
        'plant-type': 'Broadleaf Perennial Evergreen',
        'mature-size': 'Varies by species',
        'water': '',
        'sun-exposure': 'Full sun or partial shade',
        'soil-type': 'Moist but well-drained',
        'soil-pH': 'Neutral to acidic',
        'growing-season': 'Spring and Summer',
        'native-area': 'South Africa',
        'propagation': 'Yes',
        'toxicity': 'Toxic to pets.',
    },
    {
        'id': 15,
        'common-name': 'Chinese Money Plant',
        'genus': 'Pilea peperomioides',
        'care-level': 2,
        'family': 'Urticaceae',
        'plant-type': 'Evergreen Perennial',
        'mature-size': '12 in. tall',
        'water': '',
        'sun-exposure': 'Bright indirect light',
        'soil-type': 'Rich and well-draining',
        'soil-pH': 'Neutral',
        'growing-season': 'Spring',
        'native-area': 'China',
        'propagation': 'Yes',
        'toxicity': 'Considered non-toxic and pet-friendly.',
    },
    {
        'id': 16,
        'common-name': 'Corn Plant',
        'genus': 'Dracaena Fragrans',
        'care-level': 2,
        'family': 'Asparagaceae',
        'plant-type': 'Broadleaf Evergreen',
        'mature-size': '6 ft. tall (grows larger outdoors)',
        'water': '',
        'sun-exposure': 'Partial sunlight',
        'soil-type': 'Moist, well-draining, loamy',
        'soil-pH': 'Acidic',
        'growing-season': 'Fall and Spring',
        'native-area': 'Africa',
        'propagation': 'Yes',
        'toxicity': 'Toxic to pets.',
    },
    {
        'id': 17,
        'common-name': 'Birds Nest Fern',
        'genus': 'Asplenium Nidus',
        'care-level': 3,
        'family': 'Aspleniaceae',
        'plant-type': 'Perennial',
        'mature-size': '3-5 ft. tall',
        'water': '',
        'sun-exposure': 'Partial sunlight, shade',
        'soil-type': 'Loamy, moist, well-drained',
        'soil-pH': 'Acidic',
        'growing-season': 'Spring',
        'native-area': 'Asia, Australia, and Africa',
        'propagation': 'Yes',
        'toxicity': 'Considered non-toxic and pet-friendly.',
    },
    {
        'id': 18,
        'common-name': 'Ponytail Palm',
        'genus': 'Beaucarnea Recurvata',
        'care-level': 1,
        'family': 'Asparagaceae',
        'plant-type': 'Broadleaf Evergreen Shrub/Tree',
        'mature-size': '6-8 ft. tall (indoors)',
        'water': '',
        'sun-exposure': 'Full sunlight',
        'soil-type': 'Well-drained, sandy',
        'soil-pH': 'Neutral',
        'growing-season': 'Spring',
        'native-area': 'Semi-desert areas of Central America',
        'propagation': 'Yes',
        'toxicity': 'Considered non-toxic and pet-friendly.',
    },
    {
        'id': 19,
        'common-name': 'Rattlesnake Plant',
        'genus': 'Calathea Lancifolia',
        'care-level': 3,
        'family': 'Marantaceae',
        'plant-type': 'Evergreen Perennial',
        'mature-size': '30 in. tall',
        'water': '',
        'sun-exposure': 'Partial shade',
        'soil-type': 'Moist but well-drained',
        'soil-pH': 'Neutral to Acidic',
        'growing-season': 'Late Spring',
        'native-area': 'Brazil',
        'propagation': 'Yes',
        'toxicity': 'Considered non-toxic and pet-friendly.',
    },
    {
        'id': 20,
        'common-name': 'Air plant',
        'genus': 'Tillandsia',
        'care-level': 1,
        'family': 'Bromaleiaceae',
        'plant-type': 'Evergreen Perennial Flowering Plant',
        'mature-size': '2-5 in. tall',
        'water': '',
        'sun-exposure': 'Bright indirect sunlight',
        'soil-type': 'Not applicable',
        'soil-pH': 'Not applicable',
        'growing-season': 'Spring snd Summer',
        'native-area': 'North Mexico and Southern-Eastern United States, Mesoamerica, and the Carribean to mid Argentina',
        'propagation': 'Yes',
        'toxicity': 'Considered non-toxic and pet-friendly.',
    },
    {
        'id': 21,
        'common-name': 'Air Plant',
        'genus': 'Tillandsia Xerographica',
        'care-level': 1,
        'family': 'Bromaleiaceae',
        'plant-type': 'Evergreen Perennial Flowering Plant',
        'mature-size': '3 ft. tall',
        'water': '',
        'sun-exposure': 'Bright indirect sunlight',
        'soil-type': 'Not applicable',
        'soil-pH': 'Not applicable',
        'growing-season': 'Spring and Summer',
        'native-area': 'Southern Mexico, El Salvador, Guatemala, and Honduras',
        'propagation': 'Yes',
        'toxicity': 'Considered non-toxic and pet-friendly.',
    },
    {
        'id': 22,
        'common-name': 'Elephants Ear',
        'genus': 'Alocasia Macrorrhiza',
        'care-level': 2,
        'family': 'Araceae',
        'plant-type': 'Perennial Herbaceous Rhizome',
        'mature-size': '2-15 ft. tall',
        'water': '',
        'sun-exposure': 'Bright indirect lifht',
        'soil-type': 'Well-drained, loamy',
        'soil-pH': 'Slighty acidic',
        'growing-season': 'Spring and Summer',
        'native-area': 'Tropical and Subtropical regions of Asia and Eastern Australia',
        'propagation': 'Yes',
        'toxicity': 'Toxic to humans and pets.',
    },
    {
        'id': 23,
        'common-name': 'Lucky Bamboo',
        'genus': 'Dracaena Sanderiana',
        'care-level': 1,
        'family': 'Asparagaceae',
        'plant-type': 'Perennial Shrub',
        'mature-size': '1-3 ft. tall (indoors)',
        'water': '',
        'sun-exposure': 'Partial shade',
        'soil-type': 'Well-drained but moist',
        'soil-pH': 'Acidic',
        'growing-season': 'Fall and Winter',
        'native-area': 'Africa',
        'propagation': 'Yes',
        'toxicity': 'Toxic to pets.',
    },
    {
        'id': 24,
        'common-name': 'Cocoon Plant',
        'genus': 'Senecio Haworthii Mont Blanc',
        'care-level': 1,
        'family': 'Asteraceae',
        'plant-type': 'Perennial Succulent',
        'mature-size': '12 in. tall',
        'water': '',
        'sun-exposure': 'Full sunlight to partial shade',
        'soil-type': 'Sandy',
        'soil-pH': 'Fairly neutral',
        'growing-season': 'Winter and Summer',
        'native-area': 'South Africa',
        'propagation': 'Yes',
        'toxicity': 'Toxic to pets.',
    },
    {
        'id': 25,
        'common-name': 'Friends',
        'genus': 'Sansevieria Kirkii',
        'care-level': 1,
        'family': 'Asparagaceae',
        'plant-type': 'Succulent',
        'mature-size': '1 ft. tall',
        'water': '',
        'sun-exposure': 'Bright indirect light',
        'soil-type': 'Well-drained',
        'soil-pH': 'Neutral to slightly acidic',
        'growing-season': 'Spring and Summer',
        'native-area': 'East Africa',
        'propagation': 'Yes',
        'toxicity': 'Toxic to humans and pets.',
    },
    {
        'id': 26,
        'common-name': 'Green Ti Plant',
        'genus': 'Cordyline Fruticosa Glauca ',
        'care-level': 3,
        'family': 'Asparagaceae',
        'plant-type': 'Evergreen',
        'mature-size': '9-13 ft. tall',
        'water': '',
        'sun-exposure': 'Partial sunlight',
        'soil-type': 'Well-drained, loamy', 
        'soil-pH': 'Slightly acidic to neutral',
        'growing-season': 'Spring',
        'native-area': 'Southeast Asia and the Western Pacific Ocean region',
        'propagation': 'Yes',
        'toxicity': 'Toxic to humans and pets.',
    },
    {
        'id': 27,
        'common-name': 'Dragon Scale Plant',
        'genus': 'Alocasia Baginda  ',
        'care-level': 2,
        'family': 'Araceae',
        'plant-type': 'Tropical Perennial Evergreen',
        'mature-size': '3-5 ft. tall',
        'water': '',
        'sun-exposure': 'Bright indirect light',
        'soil-type': 'Well-drained',
        'soil-pH': 'Slightly acidic to neutral',
        'growing-season': 'Spring and Summer',
        'native-area': ' South-East Asia and Eastern Australia',
        'propagation': 'Yes',
        'toxicity': 'Toxic to humans and pets. ',
    },
    {
        'id': 28,
        'common-name': 'Silver Satin Pothos',
        'genus': 'Scindapsus Pictus',
        'care-level': 1,
        'family': 'Araceae',
        'plant-type': 'Perennial Vine',
        'mature-size': '4-10 ft. long',
        'water': '',
        'sun-exposure': 'Bright indirect light',
        'soil-type': 'Slightly acidic',
        'soil-pH': 'Well-drained',
        'growing-season': 'Summer',
        'native-area': 'Southeast Asia.',
        'propagation': 'Yes',
        'toxicity': 'Toxic to pets.',
    },
    {
        'id': 29,
        'common-name': 'Calathea White Fusion',
        'genus': 'Calathea Lietzei',
        'care-level': 3,
        'family': 'Marantaceae',
        'plant-type': 'Herbaceous Perennial',
        'mature-size': '1-2 ft. tall',
        'water': '',
        'sun-exposure': 'Partial sunlight',
        'soil-type': 'Moist but well-drained',
        'soil-pH': 'Neutral to acidic',
        'growing-season': 'Spring and Summer',
        'native-area': 'Tropical Americas',
        'propagation': 'Yes',
        'toxicity': 'Considered non-toxic and pet-friendly.',
    },
    {
        'id': 30,
        'common-name': 'Umbrella Plant',
        'genus': 'Schefflera',
        'care-level': 2,
        'family': 'Araliaceae',
        'plant-type': 'Broadleaf Evergreen Shrub/Tree',
        'mature-size': '4-15 ft. tall',
        'water': '',
        'sun-exposure': 'Bright indirect light',
        'soil-type': 'Rich and moderately moist',
        'soil-pH': 'Slightly acidic',
        'growing-season': 'Spring and Fall',
        'native-area': 'Australia, Taiwan, and Hainan',
        'propagation': 'Yes',
        'toxicity': 'Midly toxic to humans and pets.',
    },
    // {
    //     'id': 31,
    //     'common-name': '',
    //     'genus': '',
    //     'care-level': '',
    //     'family': '',
    //     'plant-type': '',
    //     'mature-size': '',
    //     'sun-exposure': '',
    //     'soil-type': '',
    //     'soil-pH': '',
    //     'bloom-time': '',
    //     'native-area': '',
    //     'propagation': '',
    //     'toxicity': '',
    // },
    // {
    //     'id': 32,
    //     'common-name': '',
    //     'genus': '',
    //     'care-level': '',
    //     'family': '',
    //     'plant-type': '',
    //     'mature-size': '',
    //     'sun-exposure': '',
    //     'soil-type': '',
    //     'soil-pH': '',
    //     'bloom-time': '',
    //     'native-area': '',
    //     'propagation': '',
    //     'toxicity': '',
    // },
    // {
    //     'id': 33,
    //     'common-name': '',
    //     'genus': '',
    //     'care-level': '',
    //     'family': '',
    //     'plant-type': '',
    //     'mature-size': '',
    //     'sun-exposure': '',
    //     'soil-type': '',
    //     'soil-pH': '',
    //     'bloom-time': '',
    //     'native-area': '',
    //     'propagation': '',
    //     'toxicity': '',
    // },
    // {
    //     'id': 34,
    //     'common-name': '',
    //     'genus': '',
    //     'care-level': '',
    //     'family': '',
    //     'plant-type': '',
    //     'mature-size': '',
    //     'sun-exposure': '',
    //     'soil-type': '',
    //     'soil-pH': '',
    //     'bloom-time': '',
    //     'native-area': '',
    //     'propagation': '',
    //     'toxicity': '',
    // },
    // {
    //     'id': 35,
    //     'common-name': '',
    //     'genus': '',
    //     'care-level': '',
    //     'family': '',
    //     'plant-type': '',
    //     'mature-size': '',
    //     'sun-exposure': '',
    //     'soil-type': '',
    //     'soil-pH': '',
    //     'bloom-time': '',
    //     'native-area': '',
    //     'propagation': '',
    //     'toxicity': '',
    // },
    // {
    //     'id': 36,
    //     'common-name': '',
    //     'genus': '',
    //     'care-level': '',
    //     'family': '',
    //     'plant-type': '',
    //     'mature-size': '',
    //     'sun-exposure': '',
    //     'soil-type': '',
    //     'soil-pH': '',
    //     'bloom-time': '',
    //     'native-area': '',
    //     'propagation': '',
    //     'toxicity': '',
    // },
];