
export default [
    {
        'id': 1,
        'common-name': 'Swiss Cheese plant',
        'genus': 'Monstera  Deliciosa',
        'care-level': 3,
        'family': 'Aracea',
        'plant-type': 'Tropical, climbing evergreen',
        'mature-size': '3 ft. tall',
        'sun-exposure': 'Bright indirect sunlight, partial shade',
        'soil-type': 'Peat based potting soil, well-drained',
        'soil-pH': 'Acidic or neutral',
        'bloom-time': 'Mid-summer',
        'native-area': 'Central America',
        'propagation': 'Yes',
        'toxicity': 'Toxic to cats and dogs.',
    },
    {
        'id': 2,
        'common-name': 'Baby Rubber Plant/Radiator Plant',
        'genus': 'Peperomia',
        'care-level': 2,
        'family': 'Piperacea',
        'plant-type': 'Tropical Perennial',
        'mature-size': '6-12 in. tall',
        'sun-exposure': 'Full or partial sunlight',
        'soil-type': 'Moist, well-drained soil',
        'soil-pH': 'Neutral to acidic.',
        'bloom-time': 'Summer.',
        'native-area': 'Central America, South America, & Caribbean',
        'propagation': 'Yes',
        'toxicity': 'Considered non-toxic and pet-friendly.',
    },
    {
        'id': 3,
        'common-name': 'Philodendron',
        'genus': 'Philodendron',
        'care-level': 1,
        'family': 'Araceae',
        'plant-type': 'Perennial',
        'mature-size': '1-20 ft. long',
        'sun-exposure': 'Partial sunlight',
        'soil-type': 'Well-drained loam soil',
        'soil-pH': 'Acidic',
        'bloom-time': 'Spring & Winter',
        'native-area': 'Central America, South America',
        'propagation': 'Yes',
        'toxicity': 'Toxic to pets and humans if ingested.',
    },
    {
        'id': 4,
        'common-name': 'Chinese Evergreen',
        'genus': 'Aglanoema Commutatum',
        'care-level': 1,
        'family': 'Araceae',
        'plant-type': 'Tropical Herbaceous Perennial',
        'mature-size': '1-2 ft. tall',
        'sun-exposure': 'Full or partial sunlight',
        'soil-type': 'Well-drained peaty soil',
        'soil-pH': 'Acidic',
        'bloom-time': 'Spring, Summer',
        'native-area': 'Asia',
        'propagation': 'Yes',
        'toxicity': 'Toxic to cats and dogs.',
    },
    {
        'id': 5,
        'common-name': 'ZZ Plant',
        'genus': 'Zamioculcas zamiifolia',
        'care-level': 1,
        'family': 'Araceae',
        'plant-type': 'Tropical Perennial',
        'mature-size': '3-4 ft. tall',
        'sun-exposure': 'Bright to low indirect light',
        'soil-type': 'Well-drained',
        'soil-pH': 'Neutral to acidic',
        'bloom-time': 'Spring',
        'native-area': 'Eastern Africa',
        'propagation': 'Yes',
        'toxicity': 'Midly toxic to humans and animals.',
    },
    {
        'id': 6,
        'common-name': 'Aloe Vera',
        'genus': 'Aloe Barbadensis Miller',
        'care-level': 1,
        'family': 'Asphodelaceae',
        'plant-type': 'Succulent',
        'mature-size': '1-2 ft. tall',
        'sun-exposure': 'Direct sunlight',
        'soil-type': 'Well-drained and sandy',
        'soil-pH': 'Slightly acidic',
        'bloom-time': ' Summer',
        'native-area': 'Africa, Arabian Peninsula, Madagascar',
        'propagation': 'Yes',
        'toxicity': 'Midly toxic to humans and pets.',
    },
    {
        'id': 7,
        'common-name': 'Money Tree',
        'genus': 'Pachira Aquatica',
        'care-level': 1,
        'family': 'Malvaceae',
        'plant-type': 'Tree',
        'mature-size': '20-30 ft. tall (smaller indoors)',
        'sun-exposure': 'Full sun or partial shade',
        'soil-type': 'Moist but well-drained',
        'soil-pH': 'Neutral to acidic',
        'bloom-time': 'Summer',
        'native-area': 'South America',
        'propagation': 'Yes',
        'toxicity': 'Considered non-toxic and pet-friendly.',
    },
    {
        'id': 8,
        'common-name': 'Peace Lily',
        'genus': 'Spathiphyllum',
        'care-level': 2,
        'family': 'Araceae',
        'plant-type': 'Flowering Tropical Plant',
        'mature-size': '1-3 ft. tall',
        'sun-exposure': 'Partial shade',
        'soil-type': 'Moist but well-drained',
        'soil-pH': 'Acidic',
        'bloom-time': 'Spring',
        'native-area': 'Central America, Asia',
        'propagation': 'Yes',
        'toxicity': 'Toxic to humans and pets.',
    },
    {
        'id': 9,
        'common-name': 'Pothos',
        'genus': 'Epipremnum Aureum',
        'care-level': 1,
        'family': 'Araceae',
        'plant-type': 'Tropical vine',
        'mature-size': '20-40 ft. long',
        'sun-exposure': 'Full sun or partial shade',
        'soil-type': 'Moist but well-drained',
        'soil-pH': 'Neutral to acidic',
        'bloom-time': 'Spring & Winter',
        'native-area': 'South Pacific',
        'propagation': 'Yes',
        'toxicity': 'Toxic to pets.',
    },
    {
        'id': 10,
        'common-name': 'Rubber Plant',
        'genus': 'Ficus Elastica',
        'care-level': 2,
        'family': 'Euphorbiaceae',
        'plant-type': 'Evergreen Tree',
        'mature-size': '50-100 ft. tall (smaller indoors)',
        'sun-exposure': 'Partial shade',
        'soil-type': 'Mosit but well-drained',
        'soil-pH': 'Acidic',
        'bloom-time': 'Summer',
        'native-area': 'Asia',
        'propagation': 'Yes',
        'toxicity': 'Toxic to pets.',
    },
    {
        'id': 11,
        'common-name': 'String of Hearts',
        'genus': 'Ceropegia Woodii',
        'care-level': 2,
        'family': 'Apocynaceae',
        'plant-type': 'Succulent, Vine',
        'mature-size': '1-2 ft. long',
        'sun-exposure': 'Partial sun',
        'soil-type': 'Well-drained',
        'soil-pH': 'Neutral to acidic',
        'bloom-time': 'Summer, Fall',
        'native-area': 'South Africa',
        'propagation': 'Yes',
        'toxicity': 'Considered non-toxic and pet-friendly.',
    },
    {
        'id': 12,
        'common-name': 'Snake Plant',
        'genus': 'Dracaena Trifasciata',
        'care-level': 1,
        'family': 'Asparagaceae',
        'plant-type': 'Evergreen Perennial',
        'mature-size': '6 in. to 2 ft. tall',
        'sun-exposure': 'Shade to partial sun',
        'soil-type': 'Well-drained, sandy',
        'soil-pH': 'Slightly acidic to slightly alkaline',
        'bloom-time': 'Spring',
        'native-area': 'West Africa',
        'propagation': 'Yes',
        'toxicity': 'Toxic to pets',
    },
    {
        'id': 13,
        'common-name': 'Aloe Tiki Zilla',
        'genus': 'Aloe',
        'care-level': 1,
        'family': 'Asphodelaceae',
        'plant-type': 'Succulent',
        'mature-size': '1-2 ft. tall',
        'sun-exposure': 'Direct sunlight',
        'soil-type': 'Well-drained and sandy',
        'soil-pH': 'Slightly acidic',
        'bloom-time': 'Summer',
        'native-area': 'Africa, Arabian Peninsula, Madagascar',
        'propagation': 'Yes',
        'toxicity': 'Midly toxic to humans and pets.',
    },
    {
        'id': 14,
        'common-name': 'Rattlesnake Plant',
        'genus': 'Crassula',
        'care-level': 1,
        'family': 'Crassulaceae',
        'plant-type': 'Broadleaf Perennial Evergreen',
        'mature-size': 'Varies by species',
        'sun-exposure': 'Full sun or partial shade',
        'soil-type': 'Moist  but well-drained',
        'soil-pH': 'Neutral to acidic',
        'bloom-time': 'Spring, Summer',
        'native-area': 'South Africa',
        'propagation': '',
        'toxicity': 'Toxic to pets.',
    },
    {
        'id': 15,
        'common-name': 'Chine Money Plant',
        'genus': 'Pilea peperomioides',
        'care-level': 2,
        'family': 'Urticaceae',
        'plant-type': 'Evergreen Perennial',
        'mature-size': '12 in. tall',
        'sun-exposure': 'Bright indirect light',
        'soil-type': 'Rich and well-draining',
        'soil-pH': 'Neutral',
        'bloom-time': 'Spring',
        'native-area': 'China',
        'propagation': 'Yes',
        'toxicity': 'Considered non-toxic and pet-friendly.',
    },
    // {
    //     'id': 16,
    //     'common-name': '',
    //     'genus': '',
    //     'care-level': '',
    //     'family': '',
    //     'plant-type': '',
    //     'mature-size': '',
    //     'sun-exposure': '',
    //     'soil-type': '',
    //     'soil-pH': '',
    //     'bloom-time': '',
    //     'native-area': '',
    //     'propagation': '',
    //     'toxicity': '',
    // },
    // {
    //     'id': 17,
    //     'common-name': '',
    //     'genus': '',
    //     'care-level': '',
    //     'family': '',
    //     'plant-type': '',
    //     'mature-size': '',
    //     'sun-exposure': '',
    //     'soil-type': '',
    //     'soil-pH': '',
    //     'bloom-time': '',
    //     'native-area': '',
    //     'propagation': '',
    //     'toxicity': '',
    // },
    // {
    //     'id': 18,
    //     'common-name': '',
    //     'genus': '',
    //     'care-level': '',
    //     'family': '',
    //     'plant-type': '',
    //     'mature-size': '',
    //     'sun-exposure': '',
    //     'soil-type': '',
    //     'soil-pH': '',
    //     'bloom-time': '',
    //     'native-area': '',
    //     'propagation': '',
    //     'toxicity': '',
    // },
    // {
    //     'id': 19,
    //     'common-name': '',
    //     'genus': '',
    //     'care-level': '',
    //     'family': '',
    //     'plant-type': '',
    //     'mature-size': '',
    //     'sun-exposure': '',
    //     'soil-type': '',
    //     'soil-pH': '',
    //     'bloom-time': '',
    //     'native-area': '',
    //     'propagation': '',
    //     'toxicity': '',
    // },
    // {
    //     'id': 20,
    //     'common-name': '',
    //     'genus': '',
    //     'care-level': '',
    //     'family': '',
    //     'plant-type': '',
    //     'mature-size': '',
    //     'sun-exposure': '',
    //     'soil-type': '',
    //     'soil-pH': '',
    //     'bloom-time': '',
    //     'native-area': '',
    //     'propagation': '',
    //     'toxicity': '',
    // },
    // {
    //     'id': 21,
    //     'common-name': '',
    //     'genus': '',
    //     'care-level': '',
    //     'family': '',
    //     'plant-type': '',
    //     'mature-size': '',
    //     'sun-exposure': '',
    //     'soil-type': '',
    //     'soil-pH': '',
    //     'bloom-time': '',
    //     'native-area': '',
    //     'propagation': '',
    //     'toxicity': '',
    // },
    // {
    //     'id': 22,
    //     'common-name': '',
    //     'genus': '',
    //     'care-level': '',
    //     'family': '',
    //     'plant-type': '',
    //     'mature-size': '',
    //     'sun-exposure': '',
    //     'soil-type': '',
    //     'soil-pH': '',
    //     'bloom-time': '',
    //     'native-area': '',
    //     'propagation': '',
    //     'toxicity': '',
    // },
    // {
    //     'id': 23,
    //     'common-name': '',
    //     'genus': '',
    //     'care-level': '',
    //     'family': '',
    //     'plant-type': '',
    //     'mature-size': '',
    //     'sun-exposure': '',
    //     'soil-type': '',
    //     'soil-pH': '',
    //     'bloom-time': '',
    //     'native-area': '',
    //     'propagation': '',
    //     'toxicity': '',
    // },
    // {
    //     'id': 24,
    //     'common-name': '',
    //     'genus': '',
    //     'care-level': '',
    //     'family': '',
    //     'plant-type': '',
    //     'mature-size': '',
    //     'sun-exposure': '',
    //     'soil-type': '',
    //     'soil-pH': '',
    //     'bloom-time': '',
    //     'native-area': '',
    //     'propagation': '',
    //     'toxicity': '',
    // },
    // {
    //     'id': 25,
    //     'common-name': '',
    //     'genus': '',
    //     'care-level': '',
    //     'family': '',
    //     'plant-type': '',
    //     'mature-size': '',
    //     'sun-exposure': '',
    //     'soil-type': '',
    //     'soil-pH': '',
    //     'bloom-time': '',
    //     'native-area': '',
    //     'propagation': '',
    //     'toxicity': '',
    // },
    // {
    //     'id': 26,
    //     'common-name': '',
    //     'genus': '',
    //     'care-level': '',
    //     'family': '',
    //     'plant-type': '',
    //     'mature-size': '',
    //     'sun-exposure': '',
    //     'soil-type': '',
    //     'soil-pH': '',
    //     'bloom-time': '',
    //     'native-area': '',
    //     'propagation': '',
    //     'toxicity': '',
    // },
    // {
    //     'id': 27,
    //     'common-name': '',
    //     'genus': '',
    //     'care-level': '',
    //     'family': '',
    //     'plant-type': '',
    //     'mature-size': '',
    //     'sun-exposure': '',
    //     'soil-type': '',
    //     'soil-pH': '',
    //     'bloom-time': '',
    //     'native-area': '',
    //     'propagation': '',
    //     'toxicity': '',
    // },
    // {
    //     'id': 28,
    //     'common-name': '',
    //     'genus': '',
    //     'care-level': '',
    //     'family': '',
    //     'plant-type': '',
    //     'mature-size': '',
    //     'sun-exposure': '',
    //     'soil-type': '',
    //     'soil-pH': '',
    //     'bloom-time': '',
    //     'native-area': '',
    //     'propagation': '',
    //     'toxicity': '',
    // },
    // {
    //     'id': 29,
    //     'common-name': '',
    //     'genus': '',
    //     'care-level': '',
    //     'family': '',
    //     'plant-type': '',
    //     'mature-size': '',
    //     'sun-exposure': '',
    //     'soil-type': '',
    //     'soil-pH': '',
    //     'bloom-time': '',
    //     'native-area': '',
    //     'propagation': '',
    //     'toxicity': '',
    // },
    // {
    //     'id': 30,
    //     'common-name': '',
    //     'genus': '',
    //     'care-level': '',
    //     'family': '',
    //     'plant-type': '',
    //     'mature-size': '',
    //     'sun-exposure': '',
    //     'soil-type': '',
    //     'soil-pH': '',
    //     'bloom-time': '',
    //     'native-area': '',
    //     'propagation': '',
    //     'toxicity': '',
    // },
    // {
    //     'id': 31,
    //     'common-name': '',
    //     'genus': '',
    //     'care-level': '',
    //     'family': '',
    //     'plant-type': '',
    //     'mature-size': '',
    //     'sun-exposure': '',
    //     'soil-type': '',
    //     'soil-pH': '',
    //     'bloom-time': '',
    //     'native-area': '',
    //     'propagation': '',
    //     'toxicity': '',
    // },
    // {
    //     'id': 32,
    //     'common-name': '',
    //     'genus': '',
    //     'care-level': '',
    //     'family': '',
    //     'plant-type': '',
    //     'mature-size': '',
    //     'sun-exposure': '',
    //     'soil-type': '',
    //     'soil-pH': '',
    //     'bloom-time': '',
    //     'native-area': '',
    //     'propagation': '',
    //     'toxicity': '',
    // },
    // {
    //     'id': 33,
    //     'common-name': '',
    //     'genus': '',
    //     'care-level': '',
    //     'family': '',
    //     'plant-type': '',
    //     'mature-size': '',
    //     'sun-exposure': '',
    //     'soil-type': '',
    //     'soil-pH': '',
    //     'bloom-time': '',
    //     'native-area': '',
    //     'propagation': '',
    //     'toxicity': '',
    // },
    // {
    //     'id': 34,
    //     'common-name': '',
    //     'genus': '',
    //     'care-level': '',
    //     'family': '',
    //     'plant-type': '',
    //     'mature-size': '',
    //     'sun-exposure': '',
    //     'soil-type': '',
    //     'soil-pH': '',
    //     'bloom-time': '',
    //     'native-area': '',
    //     'propagation': '',
    //     'toxicity': '',
    // },
    // {
    //     'id': 35,
    //     'common-name': '',
    //     'genus': '',
    //     'care-level': '',
    //     'family': '',
    //     'plant-type': '',
    //     'mature-size': '',
    //     'sun-exposure': '',
    //     'soil-type': '',
    //     'soil-pH': '',
    //     'bloom-time': '',
    //     'native-area': '',
    //     'propagation': '',
    //     'toxicity': '',
    // },
    // {
    //     'id': 36,
    //     'common-name': '',
    //     'genus': '',
    //     'care-level': '',
    //     'family': '',
    //     'plant-type': '',
    //     'mature-size': '',
    //     'sun-exposure': '',
    //     'soil-type': '',
    //     'soil-pH': '',
    //     'bloom-time': '',
    //     'native-area': '',
    //     'propagation': '',
    //     'toxicity': '',
    // },
];